### ISSUE TITLE
resume functionality for setup

### ISSUE THREAD

**Issue by xenigmax** [rg-korea/rainbow#10]
is required for setup.sh since it takes long time.

**Comment by soymintc** [comment]
Does this mean we have to make setup.sh faster than the current version?

**Comment by xenigmax** [comment]
@alexbmp 
If someone has to stop the process or accidently do so, the program should start from that point.

**Comment by soymintc** [comment]
Great point. I'll see to that as well. 
So that's why it's called "resume functionality"
