### ISSUE TITLE
readme.rst

### ISSUE THREAD

**Issue by xenigmax** [rg-korea/rainbow#3]
.. need an improvement

**Comment by soymintc** [comment]
Some concerns about linking the licence homepage:
1. MIT License says:
   > The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
2. Also, web search seems to recommend including a LICENSE file
   http://askubuntu.com/questions/46380/how-do-i-use-gpl-and-mit-licenses-correctly

Considering both, do you really think we should link the license URL to the README.rst? If so, why?

**Comment by xenigmax** [comment]
@alexbmp 
I didn't say we should exclude "license file".
What you did is an inclusion of "license text" to readme.rst.
That's different.

Just check this example.
https://github.com/jquery/jquery
You can find LICENSE.txt but the content is not shown in readme text.

Let me know if it's not that clear ..

**Comment by soymintc** [comment]
Ahh I totally misunderstood you. My bad.
I'll do that. And the jquery example you gave is great. Thank you.
