### ISSUE TITLE
bioperl link is broken

### ISSUE THREAD

**Issue by xenigmax** [rg-korea/rainbow#6]
http://bioperl.org/DIST/BioPerl-1.6.1.tar.gz

While doing this :
https://github.com/rg-korea/rainbow/blob/master/setup.sh#L77

---

Downloading required files
- fetching ensembl
  *\* GET https://github.com/Ensembl/ensembl/archive/release/78.zip ==> 302 Found (1s)
  *\* GET https://codeload.github.com/Ensembl/ensembl/zip/release/78 ==> 200 OK (3s)
- unpacking ./Bio/tmp/ensembl.zip
- moving files
- fetching ensembl-variation
  *\* GET https://github.com/Ensembl/ensembl-variation/archive/release/78.zip ==> 302 Found
  *\* GET https://codeload.github.com/Ensembl/ensembl-variation/zip/release/78 ==> 200 OK (3s)
- unpacking ./Bio/tmp/ensembl-variation.zip
- moving files
- fetching ensembl-funcgen
  *\* GET https://github.com/Ensembl/ensembl-funcgen/archive/release/78.zip ==> 302 Found (1s)
  *\* GET https://codeload.github.com/Ensembl/ensembl-funcgen/zip/release/78 ==> 200 OK (1s)
- unpacking ./Bio/tmp/ensembl-funcgen.zip
- moving files
- fetching BioPerl
  *\* GET http://bioperl.org/DIST/BioPerl-1.6.1.tar.gz ==> 404 Not Found
  *\* GET http://bioperl.org/DIST/BioPerl-1.6.1.tar.gz ==> 404 Not Found
  Trying to fetch using curl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  100  9340  100  9340    0     0  47296      0 --:--:-- --:--:-- --:--:-- 47411
- unpacking ./Bio/tmp/BioPerl-1.6.1.tar.gz

**Comment by soymintc** [comment]
Merged my pull request for this issue. It should be fixed now.
